### ISSUE TITLE
Version 1.0.2 changed the way SystemExit exceptions raised from do_command methods are handled

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#932] opened 2020-04-27 06:37 UTC
I have a cmd2 application which does it's own argparsing inside of the `do_command()` methods, i.e. it does not use any of the cmd2 built-in arg parsing functionality. This is done by calling `argparse.parse_args()` as one of the first lines of code inside the `do_command()` method.

In 1.0.1 if a `do_command()` method raises a `SystemExit` exception, as `parse_args()` does if given the '-h' option or if a syntax error occurs, that exception would be swallowed by `cmd2` and the command prompt would be printed again.

In 1.0.2, that exception is not swallowed and the `cmd2` app terminates.

You can replicate this issue by adding a `raise SystemExit` to the `do_speak()` method in `examples/first_app.py`, and running it with the two versions of `cmd2`.

The behavior of other raised exceptions does not appear to have changed between 1.0.1 and 1.0.2. For example if you raise a ValueError, you get:
```
EXCEPTION of type 'ValueError' occurred with message: ''
To enable full traceback, run the following command: 'set debug true'
```
in both versions of `cmd2`.

This change in behavior is caused by the change in the logic on the last two lines of the `onecmd_plus_hooks()` method made between 1.0.1 and 1.0.2.

In the short term, I request that we quickly revert this change in behavior. After that, I suggest we discuss the desired behavior is for `cmd2` when a `SystemExit` exception is raised, and then intentionally implement and document that behavior.

**Comment by kmvanbrunt** [comment] 2020-04-27 18:43
The change made to **cmd2** which resulted in this new behavior is a bug fix. `onccmd_plus_hooks()` was returning from a `finally` statement and that hid errors.

Since `SystemExit` inherits from `BaseException` instead of `Exception`, the `try` in `onecmd_plus_hooks()` will never catch it. I'm not sure it should either. If someone calls `sys.exit()`, I don't want to prevent that. Unfortunately that's exactly what `argparse` does since it was intended to be used in a non-interactive command-line utility.

I added an exception for this case. It's what our decorators raise: [Cmd2ArgparseError](https://github.com/python-cmd2/cmd2/blob/master/cmd2/exceptions.py).

`onecmd_plus_hooks()` treats this error like an `EmpyStatement`. It's silent and no `postcommand` hooks are run. 

Can you update your application to raise that upon an `argparse` error? If you need `postcommand` hooks to run, we can add a flag to the `Cmd2ArgparseError` class.

We probably need to move `Cmd2ArgparseError` to another file, since nothing in exceptions.py is part of the public API.

**Comment by kotfu** [comment] 2020-04-28 00:23
I saw no bug filed on this change to `SystemExit` behavior, just the sigint one. I understand that the error here (which I authored by the way, and I fully accept the lashing I'm due 😟 😬) prevented the implementation of the sigint fix. I'm not advocating that this change shouldn't have been made, but I don't like the process by which it happened. I can totally fix my app and resolve all of this, and it won't even be a ton of work.

But let's pretend for a moment that I was not a contributor, here's what my viewpoint would be:

- There was no bug filed documenting the offending behavior
- There was no mention of it in the changelog
- It happened in a bug fix release where I would not ordinarily be expecting major changes in functionality
- `cmd2` offers a documented way for a `do_command()` method to indicate that the application should quit: return `True`. This same documentation states that if your command method throws an exception, `cmd2` will catch it and display it for you (see https://cmd2.readthedocs.io/en/latest/features/commands.html)
- The developers are proposing an undocumented, private (i.e. not part of the declared public API) exception as the way for me to resolve the problem

**Comment by kmvanbrunt** [comment] 2020-04-28 01:08
The `onecmd_plus_hooks()` change was to fix bug #909. I don't believe it changed any functionality mentioned in the docs. We still catch and display `Exceptions` raised by `do_*` functions and we never were catching `BaseExceptions`. The return in the `finally` was eating them.

The user needed a way to stop a text script with Ctrl-C. Returning `True` from a `do_*` function stops the entire command loop. The solution was to raise a `KeyboardInterrupt` up to `runcmds_plus_hooks()` and as you know, that exposed the issue with our `finally` clause. I certainly didn't intend for that change to cause other issues and I apologize for that.

The addition of `Cmd2ArgparseError` was to fix #905. When I added it, I forgot exceptions.py wasn't public. So that's why I suggested moving it to a public file in my solution to you. However, the docstring shows I always intended it to be public.

```Python
class Cmd2ArgparseError(Exception):
    """
    Custom exception class for when a command has an error parsing its arguments.
    This can be raised by argparse decorators or the command functions themselves.
    The main use of this exception is to tell cmd2 not to run Postcommand hooks.
    """
    pass
```

While both #905 and #909 are in the change log, I didn't mention the specifics of moving the return statement since it was part of fixing #909. I can be more specific in the future.

**Comment by tleonhardt** [comment] 2020-04-29 01:06
@kmvanbrunt @kotfu What do you two think about this path forward ? ...

Near term:
- Retroactively update both the changelog and release notes to mention the specifics of the change to `SystemExit` in case anyone else is impacted
- Make `Cmd2ArgparseError` public and documented

In the future:
- We all be very careful to document bug fix changes, even if we don't anticipate there might be impact to developers
  - File a bug Issue for discoverability of anyone searching
  - Add it to the CHANGELOG and release notes
- If there is a bug fix which might possibly introduce significant changes to someone, then make it a minor release, e.g. bump to `1.10` instead of `1.0.2` in order to signal to consumers that there is a higher chance of impact
- Be careful that things developers might need to resolve issues are both public and documented

**Comment by kmvanbrunt** [comment] 2020-04-29 14:49
I agree we should add `Cmd2ArgparseError` to the public docs and edit the comment to exception.py so it no longer says:

> These are NOT part of the public API and are intended for internal use only

If we are going to retroactively update the change log, I don't think it should be so specific as to single out `SystemExit`. We had a bug that was suppressing any exception that didn't inherit from `Exception`. Those exceptions (except for `KeyboardInterrupts`) are now always raised.

Python's built-in exceptions only include 4 classes which inherit from BaseException:

> BaseException
>  +-- SystemExit
>  +-- KeyboardInterrupt
>  +-- GeneratorExit
>  +-- Exception

Therefore we raise `SystemExit` and `GeneratorExit` exceptions. I'm not sure who would be raising a `GeneratorExit` though. Additionally we raise any application-specific exceptions which do not inherit from `Exception`.

Is this the desired behavior or should we change our `except` statement to catch `BaseExceptions` and send those to `pexcept()`? A change like this would still have altered the behavior of kotfu's software. His argparse-generated `SystemExit` would have printed.

**Comment by aseemjakhar** [comment] 2020-05-06 09:04
Folks, I have the same issue as @kotfu with my project EXPLIoT - https://gitlab.com/expliot_framework/expliot

As per the discussion here, Im assuming we should catch SystemExit in our own argparse methods inside any do_*() and raise Cmd2ArgparseError? Please correct me if Im wrong.

**Comment by kmvanbrunt** [comment] 2020-05-06 13:32
@aseemjakhar 

1. `return` if you want `Postcommand` hooks to run
2. raise `Cmd2ArgparseError` if you don't

**Comment by kmvanbrunt** [comment] 2020-05-08 14:43
I posted a PR attempting to address this issue. One aspect I'm still up in the air about is handling `SystemExit`. In my initial check in, I'm doing this:

```Python
except SystemExit:
    self.pwarning("Caught SystemExit. Attempting to stop command loop...")
    stop = True
```

But I'm not sure I like this solution. It isn't consistent with the cmd2 docs that @kotfu referenced which say:

> If the command method raises an exception, cmd2 will catch it and display it for you

Plus it adds another way to stop the command loop that we have to maintain.
@tleonhardt @kotfu, What are your thoughts? Should I leave it or just change our final `except` from:
```Python
except Exception as ex:
   self.pexcept(ex)
```

to 

```Python
except BaseException as ex:
   self.pexcept(ex)
```

**Comment by tleonhardt** [comment] 2020-05-13 23:43
I'd say we should make a decision based on how would most developers expect it to behave?

If I try to pretend like I don't know anything about `cmd2` and it's just some Python library I'm new to, then I would say that I would expect that calling `sys.exit()` or equivalently raising a `SystemExit` exception to exit the application.  I would be pretty surprised if manually doing either of those did **not** exit the application.  Normally I would expect the exit to be pretty immediate, but I would be fully understanding if the framework allowed for a graceful shutdown.

So the way you have it looks OK to me.  My only question is along the lines of what @kotfu posted in the PR - once we put out a release after this change, should we bump the version to 1.1 or 2.0?  I could see an argument for either depending on whether we interpret it as a backwards incompatible change or a new feature.

**Comment by kotfu** [comment] 2020-05-14 02:02
By way of reference, in `cmd` in the standard library, if you raise SystemExit in one of your `do_command` methods, the `postcmd()` method is not called, and the application exits as you would expect.

So what if we do the same. If SystemExit is raised, the application gracefully exits (i.e. calls the appropriate post command hooks) with no fuss and no warning message. We then update the documentation so it's clear that's the behavior, with a specific reference to doing your own argparsing, which raises SystemExit, and which almost certainly you don't want to have exit the whole app.

**Comment by tleonhardt** [comment] 2020-05-14 02:22
While as an end user I would prefer a warning message giving me a clue why the app just quit when I didn’t explicitly ask it to, I wouldn’t strongly object to just quiting with no fuss as long as we document it well.

**Comment by kmvanbrunt** [comment] 2020-05-14 02:32
When you say quit with no fuss, are you ok that command finalization hooks can still override stop?

**Comment by tleonhardt** [comment] 2020-05-14 02:38
It would be odd for a developer to override stopping in a command finalization hook, but that seems fine and fair game.

**Comment by kotfu** [comment] 2020-05-14 03:05
How would the code j. The command finalization hook know that SystemExit has been raised? All it would know is that the flag has been passed as true. 

So let’s call the hook and then exit.

**Comment by kmvanbrunt** [comment] 2020-05-14 20:34
Since my previous change already inconvenienced @kotfu and @aseemjakhar, I want to make sure we have consensus and are defining terms the same way.

Questions for @kotfu 
1. When you say, "let's call the hook and exit", does **exit** mean return `True` to end the command loop or actually exit the application at that point?

2. I didn't mean the command finalization hook would know a `SystemExit` had been raised. I just meant we pass it the current value of `Stop` and it can return whatever it wants for the value of `Stop`. That value is the one returned by `onecmd_plus_hooks()`. Therefore even if a `SystemExit` is raised, the developer could theoretically always return `False` from their command finalization hook. I'm OK allowing them to do it if they really want to. This preserves existing behavior in that the command finalization hook gets the final say.

Questions for @tleonhardt 
1. How strongly do you feel about printing a warning when `SystemExit` is raised?

**Comment by kotfu** [comment] 2020-05-15 22:52
Answers for @kmvanbrunt 

1. Yes, I mean pass `True` to the the command finalization hooks, if present. If a `do_command` method raises `SystemExit`, I think we should follow the same code path as if it returns `True`.

2. Agree. we would pass the `Stop` parameter to the command finalization hooks with a value of `True`, and if the hook changes the value to `False` then the app would continue to run.

On the questions for @tleonhardt, I'll offer my opinion too :)

I like to have control of the output of my application. I'm not in favor of the framework printing stuff into the output stream for me, especially when there is no way to turn it off. If I'm a developer and I want to print warnings, I can catch the exceptions and print them myself and then re-raise. If the framework always prints the warning and I don't want it, I'm have no recourse.

**Comment by tleonhardt** [comment] 2020-05-15 22:55
@kotfu Brings up a good point.  I’m fine with not printing the warning

**Closed** 2020-05-29 21:43 UTC
