### ISSUE TITLE
failed to test my transcripts

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#518] opened 2018-09-13 16:24 UTC
As I made major changes in my app, I am removing unittests to just rely on transcript-based testing.

I have generated a transcript following https://cmd2.readthedocs.io/en/latest/freefeatures.html#transcript-based-testing then I run my script https://github.com/teto/mptcpanalyzer/blob/new_plots/tests/run_transcripts.sh (I used the absolute path to rule out any relative path problem).

```
$ tests/run_transcripts.sh 
WARNING: mptcpanalyzer may require a custom wireshark. Check github for mptcp patches streaming.
E
======================================================================
ERROR: runTest (cmd2.cmd2.Cmd.run_transcript_tests.<locals>.TestMyAppCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/1ajhfmk8kcdc3jm5f6nivsarj0dbaw63-python3.6-cmd2-0.9.4/lib/python3.6/site-packages/cmd2/transcript.py", line 53, in runTest
    self._test_transcript(fname, transcript)
  File "/nix/store/1ajhfmk8kcdc3jm5f6nivsarj0dbaw63-python3.6-cmd2-0.9.4/lib/python3.6/site-packages/cmd2/transcript.py", line 70, in _test_transcript
    line = next(transcript)
StopIteration

----------------------------------------------------------------------
Ran 1 test in 0.001s
```

I am on
```
Python 3.6.6 (default, Jun 27 2018, 05:47:41) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmd2
>>> cmd2.__version__
'0.9.4'
```

As a note to myself, it's not crystal clear how to run a shellscript instead of unittest in` pip setup.py test` but I found the trick !:  
```
cmdclass={
        "test": RunTests,
        # 'publish': 
      },
```

**Comment by tleonhardt** [comment] 2018-09-13 17:07
Hey @teto can you give us a little more information?  First off, what Linux distro (and version of distro) are you using?  Secondly, are you using Python 3.6.6 as installed from the package manager for that distro?   Or are you installing Python from somewhere else?

@kotfu is our resident transcript testing expert, but I know he has been pretty busy lately.  So any additional information you can provide us with to help us reproduce the issue would be helpful.

On another note, while I am happy you find our transcript testing useful, it isn't intended to completely replace unit testing!  It provides higher level integration/acceptance testing and is meant to complement unit testing with a framework such as ``pytest``, not replace it.

**Comment by teto** [comment] 2018-09-13 17:30
I am using nixos-unstable, thus this package https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/cmd2/default.nix and the python from the distro.

Thanks for the warning, thing is I've fiddled/am still fiddling a lot with the internals so the frontend is all that matters for now. I might put back some unittests once it settles down.

**Comment by tleonhardt** [comment] 2018-09-13 19:59
@teto By any chance could you point us in the direction of a Docker image for nixos-unstable with Python 3.6.6 installed?  I'm completely unfamiliar with NixOS and would rather not setup a whole VM if I can avoid it.

**Comment by teto** [comment] 2018-09-14 03:33
NixOS is unlike any distribution you have used before so I wouldn't inflict this upon you (it's great, just a very steep learning curve). My guess is that there is a bug in _test_transcript, the function looks complex and my transcript has commands that don't generate output. I suppose that's the reason but I will try to look deeper when I get  the time.

**Comment by kotfu** [comment] 2018-09-14 03:57
How did you generate `summary.txt`, i.e. the file containing the transcript you are using to test your app? Did you use the `history -t` command? I believe the problem in your test is caused by the single slash mark in the path of your first command in the transcript. In a transcript, a slash indicates the beginning of a regular expression. You only have a single slash in your transcript.

If this is really the cause of the problem, I think we need to provide a much better error message than we are currently providing.

As an experiment, please try creating the transcript using `history -t`, which is smart enough to escape any slashes in the generated output. Then try running your test using the new transcript and post the results.

**Comment by kotfu** [comment] 2018-09-14 04:44
I have reviewed the transcript unit tests. I think my previous idea that the single slash was causing the problem is not correct. We have a unit test which works just fine with a single slash in the command. We only check for regular expressions in the output, not the command.

I do think it would be useful to still have the transcript generated with `history -t`, so please still do that.

I also would like to further investigate @teto’s idea that a command with no output could break the transcript. We don’t have a unit test which runs a transcript with a command that doesn’t generate output.

**Comment by teto** [comment] 2018-09-14 04:48
I should have linked the transcript: https://github.com/teto/mptcpanalyzer/blob/new_plots/tests/summary.txt
The transcript  was generated through history -t.

**Comment by tleonhardt** [comment] 2018-09-14 14:37
Hmm ... when designing transcript testing, I don't think we ever considered the case where a command has no output.  I suspect that might be the issue.

**Comment by tleonhardt** [comment] 2018-09-14 16:13
I verified that the issue is caused by a command that doesn't produce any output.  I made a small change to the **alias_startup.py** example on the *fix_minor_warnings* branch and added a command called ``nothing`` which does nothing and produces no output.  I then used ``history -t`` to generate a transcript and it produce the identical error to what is reported here.

**Comment by kotfu** [comment] 2018-09-15 05:04
I can not replicate this problem. On the `transcript_fixes` branch I have created a new unit test which tests a transcript with a command which produces no output. The tests pass for me on MacOS 10.13.6 and all supported python versions. I tried to replicate the problem on the `fix_minor_warnings` branch as outlined by @tleonhardt above, and the transcript generates fine, and it replays fine.

@tleonhardt, can you post the transcript which generates an error on the `fix_minor_warnings` branch?

**Comment by teto** [comment] 2018-09-15 09:00
I added an output to the command to check if it changed anything so the new transcript looks like:
```
client_2.pcap> load_pcap examples/client_2.pcap
Loading examples\/client_2.pcap
client_2.pcap> summary 0 Client
mptcpstream 0 transferred 309
tcpstream 0 transferred 2 out of 309, accounting for 0.647249%
tcpstream 1 transferred 0 out of 309, accounting for 0.000000%
tcpstream 2 transferred 307 out of 309, accounting for 99.352751%
tcpstream 6 transferred 0 out of 309, accounting for 0.000000%
```
but yet it still fails
```
[nix-shell:~/mptcpanalyzer]$ mptcpanalyzer --test test.txt
Log level set to CRITICAL 

(mptcpanalyzer:25257): dbind-WARNING **: 17:56:49.836: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-9xRLWPr5XF: Connection refused
WARNING: mptcpanalyzer may require a custom wireshark. Check github for mptcp patches streaming.
E
======================================================================
ERROR: runTest (cmd2.cmd2.Cmd.run_transcript_tests.<locals>.TestMyAppCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/1ajhfmk8kcdc3jm5f6nivsarj0dbaw63-python3.6-cmd2-0.9.4/lib/python3.6/site-packages/cmd2/transcript.py", line 53, in runTest
    self._test_transcript(fname, transcript)
  File "/nix/store/1ajhfmk8kcdc3jm5f6nivsarj0dbaw63-python3.6-cmd2-0.9.4/lib/python3.6/site-packages/cmd2/transcript.py", line 70, in _test_transcript
    line = next(transcript)
StopIteration

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

Can it be because of my __init__ function ? https://github.com/teto/mptcpanalyzer/blob/802f4607ee7ce5cfa08887f6e7c16caa2c59f8b0/mptcpanalyzer/cli.py#L152

**Comment by tleonhardt** [comment] 2018-09-16 15:14
@kotfu Here is the transcript I tested with:
[nothing.txt](https://github.com/python-cmd2/cmd2/files/2386695/nothing.txt)

It gives the following error on macOS 10.13.6 using Python 3.7 as installed via Anaconda/conda (only platform I tested on):

    11:11 $ ./alias_startup.py -t nothing.txt
    E
    ======================================================================
    ERROR: runTest (cmd2.cmd2.Cmd.run_transcript_tests.<locals>.TestMyAppCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/toddleonhardt/src/cmd2/cmd2/transcript.py", line 53, in runTest
        self._test_transcript(fname, transcript)
      File "/Users/toddleonhardt/src/cmd2/cmd2/transcript.py", line 70, in _test_transcript
        line = next(transcript)
    StopIteration
    ----------------------------------------------------------------------

This was using the **alias_startup.py** example on the *fix_minor_warnings* branch.

**Comment by tleonhardt** [comment] 2018-09-20 00:34
@kotfu I looked into this issue a little more.  The transcript testing error only occurs when the last command in the transcript has no output.

**Comment by tleonhardt** [comment] 2018-09-30 15:40
Version 0.9.5 of ``cmd2`` will contain a fix for this bug.  Hopefully we will put this next release out to PyPI in about another week or so.

**Closed** 2018-09-30 15:45 UTC
Labels: bug

**Comment by teto** [comment] 2018-09-30 15:46
thanks !
