### ISSUE TITLE
UnicodeError when importing Cmd on macOS

### ISSUE THREAD

**Issue by Masrepus** [python-cmd2/cmd2#690] opened 2019-05-31 13:13 UTC
On High Sierra, whenever there are some "non-standard" characters in the system clipboard (e.g. 'À'), importing Cmd will crash with a UnicodeError in line 28 of clipboard.py (when trying to paste the clipboard contents into a variable). Our quickfix was to change the try-except block to catch any Exception, not just PyperclipException. But maybe the underlying problem can be solved differently.

**Comment by tleonhardt** [comment] 2019-05-31 16:09
@Masrepus Can you please provide some more information to help us reproduce your issue?  In particular:
* Version of `cmd2` you are using
* Version of Python you are using it with
* Version of Pyperclip installed
* Terminal application(s) you are using when running `cmd2`:  i.e. iTerm2
* Shell you are using:  i.e. Bash

I attempted to reproduce your issue on GitHub *master* cmd2 with Python 3.7.3 on macOS Mojave 10.14.5 with pyperclip 1.7.0 using Bash in iTerm2 and I was unable to reproduce this issue when I had `À` in the pastebuffer as you suggested.

**Comment by tleonhardt** [comment] 2019-05-31 21:58
I also tested on macOS Mojave and the latest version of `cmd2` with Python 3.5, and 3.6 and couldn't reproduce the issue as well as Python 2.7 with `cmd2` version 0.8.9 and was unable to reproduce the issue.

So @Masrepus I would very much appreciate more version info for all of the above if possible so that we can reproduce and get to the bottom of this.

**Comment by tleonhardt** [comment] 2019-05-31 22:18
@kotfu @kmvanbrunt Any data you can gather in regards to the reproducibility of this issue, either positive or negative, would be appreciated.

**Comment by Masrepus** [comment] 2019-06-03 14:51
Ah okay, so we just found out that this problem only happens when running in PyCharm. Normal bash doesn't show this behaviour, so that's probably an error of the already kind of broken PyCharm terminal emulator

**Comment by tleonhardt** [comment] 2019-06-03 15:19
@Masrepus If you try the [2019.2 EAP Early Access](https://www.jetbrains.com/pycharm/nextversion/) PyCharm build, I think they recently fixed the terminal emulator problems.  I'm using the Professional variant of that and was unable to reproduce the issue running `cmd2` apps in the terminal.

I love PyCharm and always use it for development.  But in the past I switched to [Visual Studio Code](https://code.visualstudio.com/docs/languages/python) for debugging due to the much better terminal integration.

**Comment by tleonhardt** [comment] 2019-06-03 15:20
I'm going to close this issue since it isn't a bug in `cmd2`. 

Best wishes with your `cmd2` development!

**Closed by tleonhardt** 2019-06-03 15:20 UTC
