### ISSUE TITLE
Allow modular command definition

### ISSUE THREAD

**Issue by anselor** [python-cmd2/cmd2#943] opened 2020-06-09 20:12 UTC
Allow commands to be split into multiple classes that are registered with cmd2 instead of requiring all commands to be defined in one giant class.

Breakdown:
- Define a base class for these satellite command definitions.
- Everywhere in cmd2 where it introspects for `do_`, `complete_`, or `help_` also search in the satellite command objects.
- Stretch - auto-detect all satellite command definitions (by subclass) and load them automatically on init of cmd2.Cmd.
- Example of loading a satellite command object

**Comment by muhrin** [comment] 2020-08-04 08:14
Thanks a lot for introducing this feature.  I, for one, would find this to be very useful.

In general, I think it's also a good thing for `cmd2` to move away (or at minimum provide alternatives to) to the monolithic model of putting everything in one class as this severely restricts modularity and leads to a very complex state.

If I can be of any help with testing or development, do let me know, I'd be happy to pitch in some of my time.

**Comment by muhrin** [comment] 2020-08-04 11:49
I've been playing around with this new API and I think it's very nice.  It brings some very helpful modularity to `Cmd2`.

There's one thing that I find a little awkward though, which is the interface for the `do/help/complete` functions in `CommandSet`.  Placing the `CommandSet` as the second positional argument removes some of the flexibility of being able to move a command function (without modification) from being a free function, `Cmd` member function or `CommandSet` member function.  If, however, the `CommandSet` was supplied as a keyword argument it would be possible to use the same function interchangably, e.g.:

```
def do_echo(app: Cmd, statement: Statement, *, command_set: CommandSet=None):
    ....
```
This can now be used in the following flexible ways:
```
# 1
class App(Cmd):
    <Copy/paste do_echo here>
# 2
setattr(cmd, 'do_echo', do_echo)
# 3
class Commands(CommandSet):
    <Copy/paste do_echo here>
# 4
setattr(command_set, 'do_echo', do_echo)
```
And there are no doubt others.  Point being, that there would be one unique signature for each `do/help/complete` (of course a user implementing a `Cmd` member could choose to omit the `command_set` completely knowing it will never be passed).

This becomes even more helpful when considering completer functions which I often re-use across multiple (entirely separate) commands.  Consider `Cmd2.path_completer`, this gets passed along as a `completer_method` to a parser argument.  However, this no longer works with a `CommandSet` as the second argument is going to be the the `CommantSet` instance.  I already find the existence of a `completer_function` and `completer_method` to be awkward (and additional maintenance burden).  Would it not be simpler to define one unique signature for all completers?  Namely:

`def completer(app: Cmd2, text: str, line: str, begidx: int, endidx: int, *, cmd_set: CommandSet=None)`

and those things that were `completer_functions` just ignore `app`.

**Comment by anselor** [comment] 2020-08-04 14:40
I'm a bit confused by your reference to the second parameter being CommandSet. Within a CommandSet, the `do/help/complete` functions should be CommandSet as `self`, since it is a method of CommandSet and the cmd2 app is the 2nd parameter.

**Comment by anselor** [comment] 2020-08-04 16:20
@muhrin 
We are planning on publishing what we have thus far as 1.3.0 today.

**Comment by muhrin** [comment] 2020-08-05 08:10
Thanks for getting back to me.  Sorry, my bad, I hadn't thought through the function signatures - you're quite right about `Cmd` being the second param.

I guess what I'm getting at is that there are benefits for `do/help/complete` to be designed as if they were abstract methods of an interface that both `Cmd` and `CommandSet` derive from. While this isn't technically possible (because there is no fixed function name) there are still the benefits to desining them as if it were (namely those I mentioned above).

One example of this would be to:

`def do_echo(self, statement: Statement, *, context: dict=None):`

Where context is a `dict` or `namedtuple` contaning the `Cmd` and `CommandSet` (if present).  The free function would just omit `self`.

In any case, I think the best example of this problem in action is with completers so I'll open an issue for `path_complete` specifically.

P.S. Thanks for the heads up about 1.3.0, very happy to hear it's out.

**Comment by anselor** [comment] 2020-08-05 13:48
@muhrin @kmvanbrunt @tleonhardt 
I'm re-opening this enhancement ticket for possible continued discussion.

**Comment by anselor** [comment] 2020-08-05 19:29
Bug issue #967 was filed related to this feature.

**Comment by muhrin** [comment] 2020-08-06 08:36
Thanks for re-opening.  I just wanted to follow up on the completers discussion I highlighted.

For me there are many benefits to having a common `do_`/`complete_`/`help_` definition spanning both `Cmd` and `CommandSet`.  At the moment I'm forced to care if if my method is defined in a `Cmd` or a `CommandSet` both in the way I write my function signature, but also in the way I think.

Let me sketch out a possible alternative that I mentioned:

```
class BaseCommand(metaclass=ABCMeta):
    @abstractmethod
    def perror(self, msg: Any = '', *, end: str = '\n', apply_style: bool = True) -> None:
        pass

    @abstractmethod
    def pwarning(self, msg: Any = '', *, end: str = '\n', apply_style: bool = True) -> None:
        pass

    @abstractmethod
    def pexcept(self, msg: Any, *, end: str = '\n', apply_style: bool = True) -> None:
        pass

    @abstractmethod
    def pfeedback(self, msg: Any, *, end: str = '\n') -> None:
        pass

    # ... and all other common functionality


class Cmd(BaseCommand):
    ...


class CommandSet(BaseCommand):
    def perror(self, msg: Any = '', *, end: str = '\n', apply_style: bool = True) -> None:
        return self._cmd.perror(msg, end=end, apply_style=apply_style)

    def pwarning(self, msg: Any = '', *, end: str = '\n', apply_style: bool = True) -> None:
        return self._cmd.pwarning(msg, end=end, apply_style=apply_style)

    def pexcept(self, msg: Any, *, end: str = '\n', apply_style: bool = True) -> None:
        return self._cmd.pexcept(msg, end=end, apply_style=apply_style)

    def pfeedback(self, msg: Any, *, end: str = '\n') -> None:
        return self._cmd.pfeedback(msg, end=end)

    # etc
```

This way a user needn't care if they are in a `CommandSet` or `Cmd`, they can write their commands identically.  It also has a development benefit in that many tests can be written against the common `BaseCommand` interface and automatically ran on both concrete classes.

Maybe there's something that I'm missing that would make this solution unsuitable (I'm quite new to `Cmd2`) but from what I can see this solution provides a cleaner and clearer design.

**Comment by anselor** [comment] 2020-08-06 16:08
@muhrin 
I understand what you're getting at now but there are a lot of challenges with this. 
First, cmd2 is an extension of the base Python Cmd implementation. While we've added quite a lot of features beyond Cmd, many things still fall back on the standard library implemantion. 
Second, quite a lot of things are accessed as public attributes of the cmd2 application and not through functions. It would be impossible for us to predict which specific things individuals would need from Cmd and it would be quite a lot of work to maintain all of the possible wrapper functions or properties on CommandSet. 
Third, the difference in function signature is a way of signaling to developers that this is not the same object as your cmd2 application and you will need to think about things a little bit.

You can however, declare your own base class off of CommandSet that all of your CommandSets use with the specific things you use most often wrapped as you have implemented. I think this strikes a reasonable balance between maintainability of the Cmd2 code base, providing object oriented encapsulation for a grouping of commands, while still letting you move code around between free functions, cmd2, and CommandSets with fairly minimal implementation impact.

**Comment by muhrin** [comment] 2020-08-11 08:03
@anselor 
Thanks a lot for taking a look at my suggestion.  I see that this differentiation of `Cmd` and `CommandSet` is actually by design in which case it all seems to make sense.

Your suggestion is a nice idea.  For my application it'd be great to be able to support completers and `do_` functions in a way that is agnostic to the context that they are invoked from (i.e. standard `argparse` cli from the shell, `Cmd` and `CommandSet`) so I can maximise reuse but you're right to say that I can just create my own stripped down interface that defines a the subset of common functionality.

Feel free to close this issue.

**Comment by anselor** [comment] 2020-08-12 17:07
@muhrin 
I think you may like my next change. We're going to go ahead and remove the `cmd.Cmd2` parameter as the required second parameter to the `do_`/`help_`/`complete_` functions in a CommandSet.  If you're in a CommandSet, you'll have access to the cmd2 instance through `self._cmd`. It loses the the function signature acting as a signal that something is different but does give you more flexibility in moving things around. It also reduces a redundant parameter when in CommandSet.

This is technically a breaking change, but since this feature was just introduced about a week ago I think the impact will be minimal.

**Comment by kmvanbrunt** [comment] 2020-08-12 17:11
@anselor I like removing the redundant parameter.

**Comment by muhrin** [comment] 2020-08-12 17:18
Yes! Was thinking about this redundancy too.  Certainly, for those like me that aren't using `self` in most cases this brings back the possibility to copy/paste when moving things around without having to make a signature change.

**Closed** 2020-09-09 11:00 UTC
Labels: enhancement
