### ISSUE TITLE
Abbreviations of multiline commands do not accept multiple lines

### ISSUE THREAD

**Issue by brainbarker** [python-cmd2/cmd2#102] opened 2017-05-19 15:40 UTC
After adding a command to Cmd.multilineCommands, only the full name of the command accepts multiple lines. Abbreviations of the command still work, but only accept a single line.

Example:
```python
import sys
from cmd2 import Cmd

class MLApp(Cmd):
    Cmd.multilineCommands.append('foobar')
    
    def do_foobar(self, line):
        print('foobar')

    def do_wassup(self, line):
        print('wassup')

def main():
    app = MLApp()
    app.cmdloop()

if __name__ == '__main__':
    main()
```

The output:
```
pi@raspi:~ $ python3 ~/ml_abbrev.py
(Cmd) was
wassup
(Cmd) wassup
wassup
(Cmd) foo
foobar
(Cmd) foobar
> one
> two
> ;
foobar
(Cmd)
```

**Comment by tleonhardt** [comment] 2017-05-20 06:42
@brainbarker Thanks for the detailed bug report with a good explanation of how to reproduce the problem.

So I took a close look at how everything works under the hood and I can't see any easy way to fix this perfectly.  The parsing logic which determines if a command is a multiline command or not is dependent on the full command name.  The logic which accepts abbreviated command names when it is determining what command to actually run comes into play much later.

One possible solution would be to not allow multiline commands to be abbreviated.  I could modify the logic which matches abbreviations to full command names to never match abbreviations to multiline commands and I could add a warning in the documentation mentioning that command abbreviations don't work with multiline commands.  Does that seem like an acceptable solution to you?

**Comment by tleonhardt** [comment] 2017-05-22 00:10
This was closed by #103

**Comment by brainbarker** [comment] 2017-05-23 14:59
Well, certainly not an ideal solution. It seems like it would be more
flexible if the choice of which parser to use was made after the command
itself (the actual do_ method to be called) had already been identified.
Since multiple command words (the base and any unique abbreviations) can
map to the same do_ method, you really need that information first. Perhaps
if the parsing was a two-step process: parse the first line to identify the
command, and then (if necessary) reparse with any additional lines if that
command should accept multiple lines. You could have the multiline
capability be a decorator on the do_ method then, instead of a global list
of command words.

In my case, I turned off the multiline parsing and made the do_ method read
in and parse the additional lines I needed.

Thanks for looking into the issue.

- Brian

**Comment by tleonhardt** [comment] 2017-05-23 17:24
@catherinedevlin What do you think about this issue?  You have a lot more experience with the parsing side of things.

I put in a quick-and-dirty kludge to simply disallow abbreviated multiline commands.

How difficult do you think it would be to get abbreviated multiline commands to work properly?

**Comment by tleonhardt** [comment] 2017-05-27 16:05
@brainbarker I like your idea of having the multiline capability be a decorator on the do_* method instead of a global list of command words.

I you have a good idea of how to get multiline command functionality working in a way that you would like, please feel free to submit a Pull Request.  I would be happy to work with you on this.

**Comment by brainbarker** [comment] 2017-06-03 19:02
Sounds like a good plan. Let me ponder it for a bit and get back to you when I have a workable idea.

BTW, there was another issue I was having that I haven't posted yet. As far as I can tell, the two ways of handling command "help", the help_ methods and the @Options help system, do not work together. I'll post a code example, but if you use the @Options decorator, your help_ methods no longer get called.

Thanks,
Brian
________________________________

**Comment by tleonhardt** [comment] 2017-06-04 00:35
Brian,

For **@options** commands, help for those commands is handled by the **print_help** method within the **OptionParser** class in cmd2.

The **print_help** function first prints out the docstring for the associated **do_** method and then prints out the Optparse help for that command.

It would be relatively easy to allow it to search and see if  a **help_** method exists and delegate to that.  How would you want it to behave thought?  Would you want to have the **help_** method be the sole hander for help or would you want the Optarse help to be printed after it?  Either one seems like a reasonable choice.  Regardless, let me know.  It should be a simple change one way or the other.

**Comment by brainbarker** [comment] 2017-06-04 13:05
I was hoping it would be easy to fix from within the module. I just couldn’t get it to work without changes to the cmd2 code.

Below is some code from my current project, showing some of what I was trying to do with help and options. Every command’s help_ method provides three different kinds of output: Terse help, verbose help, and the usage information. Since they all do the same thing, they all just supply the three different types of help text to a common helper method that handles the details. To make the terse vs verbose help work, I needed to override the cmd2 do_help method to add the —long option to request verbose help. Also, the method which does additional parsing and validation of the command line (the parameters to all of the commands are very similar) is passed the command’s help_ method, so that it can print just the usage information if the parameters are incorrect.

At the time, I didn’t realize that the docstring could be used for help. The examples I found online used the help_ methods. And with the three-mode help I’m using now, the docstring scheme isn’t helpful (if you’ll pardon the expression).

I like the format of the help text provided by the @options scheme, but I need to incorporate it into the help_ method output. My first thought would be to have the code for @options call the command’s help_ method, and pass in the text of the options help, so that the help_ method could add it to its output however it wanted to. In the absence of a help_ method, the existing behavior (docstring + options help) would be used.

def do_help(self, arg, opts, opts_help=None)
	where opt_help is a list of strings, so the help_ method could format the output to match what it wanted it to look like.

Here’s the bit of my code, showing what I’m doing now:


class HelpMode:
    """Poor-man's enum for the modes of the help methods"""
    #(make into an actual enum)
    TERSE, VERBOSE, USAGE_ONLY = list(range(3))

class PodApp(Cmd):
    """Command-line tool to exercise the Pods"""

    current_help_mode = HelpMode.TERSE

    def parsed_args(
            self, line, min_args=-1, max_args=-1, one_of=None,
            allow_unknown=False, only_specified=False, must_specify=False,
            help_method=None):
        """Validates the command line arguments."""
        #Calls help_method(mode=HelpMode.USAGE_ONLY) when parameters are bad.
        	pass

    def standard_help(self, terse_string, verbose_string, usage_list, mode):
        """Handle the display of the help message for standard commands"""
        if mode == HelpMode.TERSE:
            print(terse_string)
        elif mode == HelpMode.VERBOSE:
            if verbose_string:
                print(verbose_string)
            else:
                print(terse_string)

        if mode == HelpMode.USAGE_ONLY:
            prefix = ""
        else:
            prefix = "    "
        for usage in usage_list:
            print(prefix + usage)

    ### Override default help to add --long option for verbose output
    @options([make_option('-l', '--long', action="store_true", help="provide more verbose help")])
    def do_help(self, arg, opts):
        """List available commands with "help" or detailed help with "help cmd"."""
        if opts.long:
            self.current_help_mode = HelpMode.VERBOSE
        
        super(Cmd, self).do_help(arg)
        self.current_help_mode = HelpMode.TERSE

    def do_color(self, line):
        """Process the color command"""
        given_pods, args = self.parsed_args(
            line, one_of=[1, 3], must_specify=True,
            help_method=self.help_color)
        if given_pods and args:
            rgb = # blah blah

            if rgb != None:
                for pod in given_pods.values():
                    pod.set_color(rgb[0], rgb[1], rgb[2])
            else:
                self.help_color(mode=HelpMode.USAGE_ONLY)

    def help_color(self, mode=None):
        """Provide help text for this command"""
        if not mode:
            mode = self.current_help_mode
        self.standard_help(
            "Sets the color of the LEDS on the given Pods",
            "Sets the color of all of the LEDs in each given Pod to the same color. "
            	"This does not change the basecolors of the Pods, but any active color "
            	"modes are disabled.",
            [
                "usage: color [pod_spec...] <r> <g> <b>",
                "usage: color [pod_spec...] <colorname>",
                self.pod_spec_msg
            ],
            mode
        )

**Comment by tleonhardt** [comment] 2017-06-15 01:10
@brainbarker From looking at what you are trying to do regarding help, I think your best bet might be to override the **options** function which implements the **@options** decorator.

The line within it which looks like the following is what is actually setting the doctoring (and hence the help) for the returned function:

```python
new_func.__doc__ = '%s\n%s' % (func.__doc__, option_parser.format_help())
```

You could modify that do do something else.  If your decorator-fu is strong, you could probably do something tricky and awesome.  But my decorator-fu is weak, so I'm afraid I can't help you much here ;-)

If you have a good idea of how to modify the existing cmd2 code to meet your needs where it won't break existing uses, then please feel free to submit a pull request.

**Comment by tleonhardt** [comment] 2017-06-21 12:27
@brainbarker I'm going to close this issue for now.  Please feel free to submit a Pull Request for either of the issues we have discussed.

**Closed by tleonhardt** 2017-06-21 12:27 UTC
Labels: bug, documentation, question
