### ISSUE TITLE
Help Scoping

### ISSUE THREAD

**Issue by pseudorandomname** [python-cmd2/cmd2#801] opened 2019-11-08 16:32 UTC
I am working on building an application using cmd2.  I am struggling to understand how to control scoping on help text.  When I create a command that uses arguments, good to go.  For a command that when fully provided looks like this: ```root_cmd sub_cmd sub_cmd_argument```, if sub_cmd_argument is missing, I get this:
```
> root_cmd sub_cmd
Error: the following arguments are required: sub_cmd_argument
```
Perfect.

But when a subcommand argument is missing, it gives me the help text for the outer-most command.  So for a command that when fully provided looks like this: ```root_cmd sub_cmd sub_cmd2```, if sub_cmd2 is missing, I get this:
```
> root_cmd sub_cmd
This is the help for root_cmd
```
But what I really want in this case is:
```
> root_cmd sub_cmd
This is the help for sub_cmd
```

How do I accomplish this?

**Comment by tleonhardt** [comment] 2019-11-09 15:56
@pseudorandomname Thanks for reporting an interesting and apparently subtle issue.  

@kmvanbrunt This sounds very much up your alley.

**Comment by kmvanbrunt** [comment] 2019-11-09 16:37
@pseudorandomname Can you post some sample code that reproduces what you are seeing? Also, what version of **cmd2** are you using?

**cmd2** has built-in commands which I think follow the same structure you are describing and I receive the expected help strings. For instance, `alias` has 3 subcommands `(create, delete, list)`. 

```
> (Cmd) alias 
Usage: alias [-h] {create, delete, list} ...
Error: the following arguments are required: subcommand

> (Cmd) alias create 
Usage: alias create [-h] name command ...
Error: the following arguments are required: name, command, command_args 
```

**Comment by pseudorandomname** [comment] 2019-11-11 16:14
hi @kmvanbrunt, thanks for your speedy reply!

Here is a program that reproduces the problem on my machine:
```
#!/usr/bin/env python3
# coding=utf-8
import argparse
import random
import cmd2
class CmdLineApp(cmd2.Cmd):
    parser = cmd2.Cmd2ArgumentParser(prog='root')
    subparser = parser.add_subparsers(title='root title')
    cmd_parser = subparser.add_parser('command', help='command help')
    cmd_parser.add_argument('sub_arg', help='sub_arg help')
    cmd_parser.add_argument('identifier', help='the id of the thing to do the command to')
    cmd_subparser = cmd_parser.add_subparsers(title='command subparsers', dest='cmd_type')
    opt1 = cmd_subparser.add_parser('opt1')
    opt2 = cmd_subparser.add_parser('opt2')
    opt2_subparser = opt2.add_subparsers(title='opt2 subparsers', dest='opt2_type')
    opt2_a = opt2_subparser.add_parser('a', help='a help')
    opt2_b = opt2_subparser.add_parser('b', help='b help')

    @cmd2.with_argparser(parser)
    def do_root(self, args):
        print("IN ROOT")

if __name__ == '__main__':
    import sys
    c = CmdLineApp()
    sys.exit(c.cmdloop())
```
The output looks like this, when using cmd2 version 0.9.19:
```
(Cmd) root command my_id opt1
IN ROOT
(Cmd) root command my_id opt2
IN ROOT
(Cmd) root command my_id opt2 --help
Usage: root command [-h] sub_arg identifier {opt1, opt2} ...

positional arguments:
  sub_arg       sub_arg help
  identifier    the id of the thing to do the command to

optional arguments:
  -h, --help    show this help message and exit

command subparsers:
  {opt1, opt2}

(Cmd) quit
```
When I say `root command my_id opt2 --help`, I expected information about opt2_a and opt2_b to show, as I hoped the help would be scoped to opt2.  

It occurs to me that I really asked two questions in my original post without realizing it. In addition to the help scoping problem, I do not know how to make it required that either opt2_a or opt2_b must be supplied, but not both.  I suspect that would be an argparse thing, rather than a cmd2 thing right?  My assumption was originally that omitting opt2_a and opt2_b would result in the help being displayed for opt2.

**Comment by tleonhardt** [comment] 2019-11-11 16:26
@pseudorandomname In regards to your question about how to make it required that either `opt2_a` or `opt2_b` must be supplied but not both, I believe you are searching for the `argparse` [mutually exclusive group](https://docs.python.org/3/library/argparse.html#mutual-exclusion) feature.

**Comment by kmvanbrunt** [comment] 2019-11-11 17:34
@pseudorandomname What you are seeing is argparse's help text and, other than some whitespace, is not affected by cmd2's code.

Here is a non-cmd2 Python app to demonstrate
```Python
#!/usr/bin/env python3
# coding=utf-8
import argparse

parser = argparse.ArgumentParser(prog='root')
subparser = parser.add_subparsers(title='root title')

cmd_parser = subparser.add_parser('command', help='command help')
cmd_parser.add_argument('sub_arg', help='sub_arg help')
cmd_parser.add_argument('identifier', help='the id of the thing to do the command to')

cmd_subparser = cmd_parser.add_subparsers(title='command subparsers', dest='cmd_type')
opt1 = cmd_subparser.add_parser('opt1')
opt2 = cmd_subparser.add_parser('opt2')

opt2_subparser = opt2.add_subparsers(title='opt2 subparsers', dest='opt2_type')
opt2_a = opt2_subparser.add_parser('a', help='a help')
opt2_b = opt2_subparser.add_parser('b', help='b help')

parser.parse_args()
```

Run `./my_app.py command my_id opt2 --help` to see it print the same text as your cmd2 app

You issue is that `root -> command` has two arguments expected to come before the `opt2` subcommand and you are only supplying one of them. So opt2 is being interpreted as the value supplied for `identifier`.

It should be `root command sub_arg my_id opt2 --help`

**Comment by kmvanbrunt** [comment] 2019-11-15 02:52
@pseudorandomname 
I'm closing this issue for now since the question was answered. Feel free to follow up if you have more questions.

**Closed by kmvanbrunt** 2019-11-15 02:52 UTC
Labels: question
