### ISSUE TITLE
prompt not displaying in pycharm

### ISSUE THREAD

**Issue by timothy-netapp** [python-cmd2/cmd2#1027] opened 2020-12-04 13:08 UTC
I'm running cmd2 1.4.0 on a Mac with python 3.8 using conda environment.  When I run inside pycharm IDE, the prompt does not display.  Running it from bash shell works fine.  The prompt works when I use the older cmd package inside pycharm.  This is a pain since I do all my dev work inside pycharm.  Likely something that pycharm is doing, but hoping for a work around.

**Comment by anselor** [comment] 2020-12-04 14:05
Maybe @tleonhardt or @kmvanbrunt have some insights on this. I use PyCharm as well and I just run it externally and attach to it if I need to debug. I seem to recall @tleonhardt said that VS Code does show the prompt correctly in their built-in terminal emulator. I didn't like VS Code as much as PyCharm when I tried it.

**Comment by marc-haberstroh** [comment] 2020-12-04 21:48
I see the same issue described when running in Eclipse/PyDev. The Eclipse console doesn't show the prompt. Prompt does display when run from bash.

**Comment by tleonhardt** [comment] 2020-12-05 00:56
@timothy-netapp Can you please provide some more information, in particular the following:
- Version of PyCharm
- Version of MacOS
- How you are running within PyCharm
- Default terminal

In older versions of PyCharm, the terminal didn't work well, but in newer versions I've never had a problem. 

I just tested using the following setup and was unable to reproduce the problem:
- macOS Big Sur 11.0.1
- PyCharm Professional 2020.3
- cmd2 1.4.0 (latest from GitHub)
- Run cmd2 application in `Terminal` tab within PyCharm (in a virtual env setup and maintained by Pipenv)
- Python 3.8.6

**Comment by timothy-netapp** [comment] 2020-12-05 02:17
I'm running
MacOS Catalina 10.15.7
PyCharm : I was running PyCharm 2020.2.3 (Professional Edition) I just upgraded to 2020.3 and same problem
I use Conda virtual environment with Python 3.8.5
I run it using the run configurations so I can have different command line args to test with and just hit ^r to run or ^d to debug so it runs inside the "Run" tab within the IDE.  If I manually run it in "Terminal" then it works, but that's the same as running from the shell.
The shell is actually zsh (I'm so used to calling it bash)
I use VSCode for when I am using jenkins/groovy, but the vcs tools are extremely lacking

**Comment by timothy-netapp** [comment] 2020-12-05 02:38
Also, I just installed python 3.8.6 directly from python.org and set up a non-Conda virtual environment.  Still no prompt in the run tab.  My IT Dept has not blessed Big Sur yet nor do I really want to jump on that for a while.

**Comment by tleonhardt** [comment] 2020-12-05 02:57
@timothy-netapp Thanks for all the info - that explains it and there is a really easy fix.  By default when you are running in PyCharm using either `run` or `debug`, it doesn't actually really emulate a terminal.  However, there is a box you can check in "Edit Configurations" under the *Execution* section called **Emulate terminal in output console**.

Check that box and everything should just work ;-)

**Comment by tleonhardt** [comment] 2020-12-05 03:01
On an unrelated note, the default version control integration in VSCode is crap.  But the [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) extension is excellent and makes it worlds better.

**Comment by tleonhardt** [comment] 2020-12-15 02:48
@timothy-netapp I'm going to close this since I think I documented the simple checkbox fix.  If you are still having problems, feel free to re-open it.

**Closed by tleonhardt** 2020-12-15 02:48 UTC
