### ISSUE TITLE
Move main.py to cmd2/__main__.py

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#487] opened 2018-07-31 05:30 UTC
We have a file at the top level of the source distribution called `main.py` which launches an instance of `cmd2.Cmd()`. Interesting, but I don't see how anyone but a developer could actually run it. I think it should go in `cmd2/__main.py` so you can do something like:

`
$ python -m cmd2
`

**Comment by tleonhardt** [comment] 2018-07-31 05:42
The ``main.py`` example at the top-level was intended to be an absolute bare-bones example of using ``cmd2.Cmd`` in a ``cmdloop`` and was intended to be used by a developer for debugging and troubleshooting purposes.

That being said, it shouldn't exist at the top level.  I could see moving it either into **examples** and renaming it or moving it into **cmd2** as you suggest.  I don't see any harm into moving it into **cmd2**, though I'm not sure how much use it would be to an end user who isn't maintaining ``cmd2``.

**Comment by anselor** [comment] 2018-10-06 18:09
I vote for just moving it to examples as a hello world - maybe call it hello_cmd2.py. Moving it inside of cmd2 wouldn't really make any sense to users since it's not intended to be directly executed.

**Comment by tleonhardt** [comment] 2018-10-06 18:12
I’m game with just moving it inside examples.  The intent of it is to be a fairly bare-bones cmd2 application, but one suitable for quick manual testing and debugging.

**Closed** 2018-10-10 00:04 UTC
Labels: enhancement, minor
