### ISSUE TITLE
test_path_completion_user_expansion fails when $HOME is /

### ISSUE THREAD

**Issue by felixonmars** [python-cmd2/cmd2#171] opened 2017-07-05 03:25 UTC
```
_____________________ test_path_completion_user_expansion ______________________

cmd2_app = <cmd2.Cmd object at 0x7f856ded3828>

    def test_path_completion_user_expansion(cmd2_app):
        # Run path with just a tilde
        text = ''
        if sys.platform.startswith('win'):
            line = '!dir ~\{}'.format(text)
        else:
            line = '!ls ~{}'.format(text)
        endidx = len(line)
        begidx = endidx - len(text)
        completions_tilde = cmd2_app.path_complete(text, line, begidx, endidx)

        # Run path complete on the user's home directory
        user_dir = os.path.expanduser('~')
        if sys.platform.startswith('win'):
            line = '!dir {}'.format(user_dir)
        else:
            line = '!ls {}'.format(user_dir)
        endidx = len(line)
        begidx = endidx - len(text)
        completions_home = cmd2_app.path_complete(text, line, begidx, endidx)

        # Verify that the results are the same in both cases
>       assert completions_tilde == completions_home
E       AssertionError: assert ['/python-cmd2/'] == ['python-cmd2/']
E         At index 0 diff: '/python-cmd2/' != 'python-cmd2/'
E         Use -v to get the full diff

tests/test_completion.py:257: AssertionError
```

**Comment by tleonhardt** [comment] 2017-07-05 13:06
@felixonmars Could you please provide more information regarding the specific environment you encountered this problem in including OS name and version and Python version?

I tested this on the following setups and was unable to reproduce the problem ( and I both tried manually exporting HOME to be "/" and hard-coding the user_dir in the unit test to be "/" just to be sure):

- Debian 8.8 with Python 3.4
- Mac OS 10.12 with Python 3.6
- Mac OS 10.12 with Python 2.7

**Comment by tleonhardt** [comment] 2017-07-05 15:40
@felixonmars Thanks for the bug report!

I have now managed to reproduce the issue on my end.  The problem occurs when we expand a user path and there is only a single tab-completion result.  We will look into it further and work on a fix.

Thanks again for finding this subtle issue!

**Comment by tleonhardt** [comment] 2017-07-05 16:08
After looking into the issue some more, this is a bug in our unit test itself.  The actual behavior at the command-line works as intended. 

I will push a fix for this shortly.

**Closed** 2017-07-05 16:14 UTC
Labels: bug

**Comment by tleonhardt** [comment] 2017-07-05 17:07
@felixonmars If you can pull the last commit and test it on your end, I would appreciate it.

Thanks again!

**Comment by felixonmars** [comment] 2017-07-06 01:44
Confirmed the fix, thanks so much :D
