### ISSUE TITLE
what version does cmd2 appear as when 

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#574] opened 2018-10-11 02:51 UTC
Hi,

I wanted to use the development version on nix to check if it solved my transcript issues (I wanna release my software soon so I am updating tests). 
My problem is that cmd2's version appears as 0.1.dev1+gf38e100.d20181011 with scm see:
https://github.com/NixOS/nixpkgs/issues/48146
I don't know how  `use_scm_version=True` works but would it be possible to have it emit 0.9.dev+gf38e100.d20181011 instead (assuming it gives the same result on less exotic distribs like debian/ubuntu) ?

**Comment by teto** [comment] 2018-10-11 03:02
When fetching cmd2 from a local folder, I correctly get 0.9.5.dev385+gf38e100, weird... but at least it works. For the record, it's possible to influence the version scheme with` {"version_scheme": "post-release",`

So I've another question, I run the following transcript
```
server_2_filtered.pcapng> load_pcap examples/server_2_filtered.pcapng
Loading examples\/server_2_filtered.pcapng
server_2_filtered.pcapng> summary 0 Client
mptcpstream 0 transferred 308 bytes.
tcpstream 0 transferred 308 bytes out of 308, accounting for 100.00%
tcpstream 2 transferred 0 bytes out of 308, accounting for 0.00%
tcpstream 6 transferred 0 bytes out of 308, accounting for 0.00%
server_2_filtered.pcapng> summary 0 Server
mptcpstream 0 transferred 461 bytes.
tcpstream 0 transferred 456 bytes out of 461, accounting for 98.92%
tcpstream 2 transferred 5 bytes out of 461, accounting for 1.08%
tcpstream 6 transferred 0 bytes out of 461, accounting for 0.00%
```
 via this command `mptcpanalyzer --test /home/teto/mptcpanalyzer/tests/summary_server_2_filtered.txt`
but the output is just one line ?

```
>>> 6 transferred 0 bytes out of 461, accounting for 0.00%
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK

```
is this expected ?

**Comment by kotfu** [comment] 2018-10-15 00:43
@teto on your transcript testing question, that is the expected output. When `cmd2` runs a transcript via the **--test** command line option, it actually creates a simple `pytest` class which has a single test. That test checks the entire output of the transcript. You can validate the intended behavior from the `cmd2` source tree:
```
$ cd examples
$ python example.py --test ../tests/transcripts/spaces.txt
```

The **spaces.txt** transcript has multiple commands, but the output is just a single pytest test:
```
.
----------------------------------------------------------------------
Ran 1 test in 0.020s

OK
```

I'm not sure why your output has the
```
>>> 6 transferred 0 bytes out of 461, accounting for 0.00%
```
part, but it's not coming from `cmd2`.

**Comment by kotfu** [comment] 2018-10-15 01:03
On the `setuptools_scm` issue, I think it could be the way that NixOS retrieves the source from GitHub. `setuptools_scm` works by examining the git metadata at package time. I don't know how the NixOS build process works, but say it retrieves a tarball of the given commit (like `git archive` would do), instead of cloning the entire repository. This would make sense for a OS that builds everything from source (which it appears NixOS is) because it would save a ton of bandwidth and time during the build process. If that's what it's doing for `cmd2`, then `setuptools_scm` will not have any git metadata to use to calculate the version number at packaging time, and will revert to 0.1.0. Which is what it looks like is happening.

Is there a way to instruct the NixOS build process to clone the whole repo?

**Comment by tleonhardt** [comment] 2018-10-15 01:45
I tested installing from GitHub with pip on Debian 9.5 and it had a reasonable version.  So I think the issue installing from GitHub not having the right version must be specific to NixOS.  So I am going to close this issue.

**Closed by tleonhardt** 2018-10-15 01:45 UTC
Labels: question

**Comment by teto** [comment] 2018-10-15 01:56
thanks for the answers. 

I knew about having to fetch the git folder too since I had had the same problem on another repository (https://github.com/NixOS/nixpkgs/issues/41136). Basically you have to do (for others):
```
           src = super.fetchgit {
            url=https://github.com/python-cmd2/cmd2.git;
             rev = "f38e100fd77f4a136a4883d23b2f4f8b3cd934b7";
            sha256 = "0nc15i1628y66030d0b2g3xriyhxps5v8s9y1d6kx8jp1ccwvyfz";
             leaveDotGit = true;
           #  deepClone = true;
           };
```
and add git to the nativeBuildInputs.
Yet I still had the problem with cmd2. I will try later as I am tight now.

@kotfu 
`>>> 6 transferred 0 bytes out of 461, accounting for 0.00%` comes from my program, I am almost sure it's a self.poutput call which is why I was I surprised to only see that one (I expect either to see all or none but just one felt weird hence my question).
Thanks
