### ISSUE TITLE
Allow readline.__file__ to be missing

### ISSUE THREAD

**Issue by jayvdb** [python-cmd2/cmd2#802] opened 2019-11-10 11:27 UTC
See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.

Currently cmd2 fails under PyOxidizer with:

```py
  File "cmd2", line 15, in <module>
  File "cmd2.cmd2", line 56, in <module>
  File "cmd2.rl_utils", line 120, in <module>
AttributeError: module 'readline' has no attribute '__file__'
```

If `sys.oxidized` is set, and `readline` is imported (and isnt libedit), then any symbols needed are in the binary, if that is helpful.

**Comment by tleonhardt** [comment] 2019-11-10 23:20
Getting `cmd2` to interoperate properly with [PyOxidizer](https://github.com/indygreg/PyOxidizer) would likely not be a trivial thing to do due to some of the *interesting* design choices made by `PyOxidizer`.  It seems like it would be possible, but honestly I don't see a way to do it reliably without moving to Python 3.8.  

Changes which would appear to be required include the following:
* Replace usage of `pkg_resources` in [__init__.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/__init__.py) since this module doesn't appear to be available within `PyOxidizer` applications (found by my testing)
    * We use this in combination with [setuptools_scm](https://github.com/pypa/setuptools_scm) for managing the `cmd2` package version
    * Python 3.8 appears to have an [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) module which could probably fill the need, but that doesn't  exist prior to 3.8
    * Another option would be to re-design how `cmd2` versions are done, but this would be a significant refactoring which I don't believe we would like to undertake
* Replace usage of `__file__` in [rl_utils.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/rl_utils.py) as you mention
    * Here we just need to get the path to a C code dynamic library so we can load it with [ctypes](https://docs.python.org/3/library/ctypes.html), we do **NOT** want to open the file, nor do we want to create it
    * It looks like [importlib.resources](https://docs.python.org/3/library/importlib.html) is the recommended way to load "resource" files when using `PyOxidizer`, but I don't see any suitable APIs there for this
    * It does look like [importlib.util.find_spec()](https://docs.python.org/3/library/importlib.html#importlib.util.find_spec) would do what we want for finding the underlying dynamic library, but it is unclear to me if this would be properly supported within `PyOxidizer`

@kmvanbrunt @kotfu What are your thoughts?  Do you have any smart ideas on how we can support it?

For developers wishing to package a `cmd2` application, we can recommend all of the following based on personal and professional experience:
* Deploy your Python app using a [Docker container](https://runnable.com/docker/python/dockerize-your-python-application)
  * Powerful and flexible - allows you to control entire user space and setup other applications like databases
* [PyInstaller](https://www.pyinstaller.org)
  * Quick and easy - it "just works" and everything you need is installable via `pip`
* [Nuitka](https://nuitka.net)
  * Converts your Python to C and compiles it to a native binary
* [Conda Constructor](https://github.com/conda/constructor)
  * Allows you to create a custom Python distro based on miniconda

**Comment by jayvdb** [comment] 2019-11-10 23:39
The key difference is that PyOxidizer pulls in libs and compiles them into the static binary.  Nuitka also can do static binaries, but that isnt as integrated yet. (btw, you might be interested in trying `staticx`)
I guess cmd2 needs some readline symbols.  Is there documentation about what it needs?  Or does it really need a shared lib readline?  Can it degrade gracefully without readline?

`importlib.metadata` has a backport `importlib_metadata`; likewise `importlib.resources` has backport `importlib-resources`, but `pkgutil.get_data` can also be used to be backwards compatible without the backport.  I expect that `pkg_resources` will be solved soon in PyOxidizer (I have a hacky fix for it)

**Comment by kmvanbrunt** [comment] 2019-11-11 03:29
@jayvdb cmd2 uses readline functions which are not exposed by the Python readline wrapper to enable some of our more advanced tab-completion features as well as asynchronous alert functions. The only way to access these functions is to call directly into readline's shared library.

How does PyOxidizer support `ctypes.CDLL()` and `ctypes.LoadLibrary()` functions which most likely call `LoadLibrary()` on Windows and `dl_open()` on Linux? Both of these OS functions load shared libraries from disk.

As @tleonhardt suggested, I can change the `__file__` usage to `importlib.util.find_spec('readline').origin`, but will PyOxidizer support that?

**Comment by jayvdb** [comment] 2019-11-11 04:52
In PyOxidizer, there is no shared readline lib. It is is statically linked into the binary `sys.executable`. The features cmd2 uses are in the binary, somewhere ;)

Could you give me an example symbol which is critical for cmd2, and I'll check how to get it.

**Comment by kmvanbrunt** [comment] 2019-11-11 15:39
@jayvdb It doesn't seem like PyOxidizer fully supports the Python standard library since `ctypes.CDLL()` and `ctypes.LoadLibrary()`, which both expect to load shared libraries from disk, won't work.

cmd2 isn't doing anything non-standard nor is the use of `__file__` incorrect since Python's docs say:

> The __file__ attribute may be missing for certain types of modules, such as C modules that are statically linked into the interpreter; **for extension modules loaded dynamically from a shared library, it is the pathname of the shared library file**.

**Comment by kmvanbrunt** [comment] 2019-11-11 15:46
@jayvdb 
Here are the symbols we use from the readline.so file.

- rl_basic_quote_characters
- rl_display_match_list
- rl_forced_update_display
- rl_display_fixed
- rl_point
- rl_set_prompt

**Comment by kmvanbrunt** [comment] 2019-11-15 03:10
@jayvdb We'd like to close this issue in a few days unless you have any more suggestions. Since our code in this case is using a standard Python library function, we'd prefer any suggestions to be compatible with Python and not introduce special-case code or third party dependencies.

**Comment by jayvdb** [comment] 2019-11-15 07:13
As shown, it is trivial to degrade gracefully.
Using an optional attribute without a guard is not ok.
Getting readline working will be a bit more challenging, but that is less critical.

**Comment by kmvanbrunt** [comment] 2019-11-15 22:49
@jayvdb 

> Using an optional attribute without a guard is not ok.

I don't agree that `__file__` is optional. The problem is the PyOxidizer's [issue](https://github.com/indygreg/PyOxidizer/issues/69) only quotes half a sentence from Python's docs.

The whole thing says the following:
> The __file__ attribute may be missing for certain types of modules, such as C modules that are statically linked into the interpreter; **for extension modules loaded dynamically from a shared library, it is the pathname of the shared library file**.

The Python readline module is an extension module loaded from a shared library. So cmd2 is correct to assume `__file__` with be populated in the imported module and contain the path to the `.so` file.

> As shown, it is trivial to degrade gracefully.
Getting readline working will be a bit more challenging, but that is less critical.

I agree it's trivial to handle the exception gracefully, but I don't agree that removing readline support isn't critical.

In [rl_utils.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/rl_utils.py), we gracefully handle the case where readline can't be imported. If that occurs, we print a warning to the user that contains a solution.

>  Readline features including tab completion have been disabled since no supported version of readline was found. To resolve this, install pyreadline on Windows or gnureadline on Mac.

It's easy for a user to fix this problem and be able to use all features of cmd2.

If we add your change, there is no warning we could print that includes a solution. The user experience of cmd2 would be severely degraded. Tab completion, and especially its integration with argparse, are core features of cmd2 applications. Other powerful features like asynchronous alerts and dynamic prompt updating would also be missing. Scripting and transcript testing would still work, but I think most applications include an interactive CLI portion.

Are you a user or developer of a cmd2-based application? What features do you currently rely on?

The root of this problem is PyOxidizer's limited support for extension modules. Their [status](https://pyoxidizer.readthedocs.io/en/latest/status.html) page says they intend to add support for `__file__`. At that time, then it would be appropriate to include a cmd2-based application in a PyOxidizer distribution.

**Comment by jayvdb** [comment] 2019-11-16 02:54
@kmvanbrunt

> I don't agree that __file__ is optional. 

That is a very lonely argument.  You are factually wrong!  You need to read up on how the import system happens now, and everywhere in this issue where you see "PyOxidizer", replace it with custom CPython which has modified `Modules/Setup` to include readline statically by uncommenting [this line](https://github.com/python/cpython/blob/0a18ee4/Modules/Setup#L164).  You can not argue that CPython isnt supposed to do this.  The assumption that readline is shared is *usually* true, but not guaranteed, and thus it is optional, and you need to guard use of `__file__`.

Also Nuitka static builds, which I am pretty sure you have not tried, also will very likely fail.

> Are you a user or developer of a cmd2-based application?

I am a developer.  Including a Nuikta and PyOxidizer developer, and I can tell you there is no `__file__` solution for this -- only ugly hacks, and we want to avoid going down the same crazy path as PyInstaller which are inefficient, error prone, and fail to clean up if a process is killed.

> What features do you currently rely on?

I rely on it NOT failing with a `NameError` during import.  You know that imports are not supposed to fail with NameError, right?

> If we add your change, there is no warning we could print that includes a solution.

The warning could link to this issue, indicating it is an unsolved problem.  Then developers trying to implement freeze solutions which statically link will encounter the message way before the theoretical user that you are trying to help.

But you are also wrong here.  As I mentioned above, PyOxidizer supports loading packages outside of the binary (as does Nuitka static), so the user could include gnureadline in the `PYTHONPATH`.  There is small problem in PyOxidizer with loading shared lib modules from outside of the binary, so atm gnureadline wont load, but that is solvable (and the solution is almost the same as the one at https://github.com/indygreg/PyOxidizer/issues/180)

> The user experience of cmd2 would be severely degraded.

Yes, it would.  But at least the invocation of a static binary wont fail with a `NameError`.  The developers of the cli app can then adapt their static binary to the fact that `cmd2` isnt full functional.

> The root of this problem is PyOxidizer's limited support for extension modules.

The root of the problem is that cmd2 is using C symbols in a shared libs provided by CPython which doesnt include those C symbols in its exported public interface.

The real solution is for cmd2 to have a small Cython shim which links against readline and exposes those symbols.  I havent had time to do that yet, as I am still investigating a hackier approach of trying to reach those C symbols from inside the static binary, which should work on Windows, but I haven't got it working on Linux yet.

**Comment by kmvanbrunt** [comment] 2019-11-16 04:00
@jayvdb Your condescension isn't welcome.

Are you actually writing a cmd2-based application or are you only posting on our site because you're aware of a crash? If you are writing a CLI, why choose cmd2 since you won't get the majority of our custom features once readline is disabled?

**Comment by jayvdb** [comment] 2019-11-16 04:52
You keep accusing PyOxidizer of being at fault, despite several attempts at clarifying this for you, and even threatening to close the issue.

I am trying to get an existing CLI which already uses cmd2 to work.

The alternative is to rip out cmd2 from any app which needs to work in the embedded world.

I keep explaining that getting readline working with cmd2 is not terribly difficult, but that is a separate enhancement from avoiding crashes which the first patch https://github.com/python-cmd2/cmd2/pull/807 does, and what this issue is about.

Please review the PR.

**Comment by kmvanbrunt** [comment] 2019-11-16 05:19
@jayvdb I will review the merge request. Let us know when you have suggestions on how the readline symbols can be used without directly accessing a shared library file using `ctypes`.

**Comment by jayvdb** [comment] 2019-11-16 05:35
I've already answered that question a few times in this issue, providing two approaches which should work broad terms.

**Comment by jayvdb** [comment] 2019-11-16 06:15
For the record, three of my comments on this issue, which explained the problem in more detail and described solutions, have been removed.

**Comment by kmvanbrunt** [comment] 2019-11-16 06:26
cmd2 is designed to work on Linux and Mac in a standard CPython environment which provides ctypes and a GNU readline shared library file. We are OK with whatever limitations this causes for custom runtime environments. No code changes will be made at this time since we don't wish to support cmd2 running with a significant loss of features.

**Comment by kmvanbrunt** [comment] 2019-11-17 01:15
I'll add exception handling so cmd2 won't crash in a PyOxidizer environment. The CLI will be missing a lot of features, but it will work.

**Comment by tleonhardt** [comment] 2019-11-17 20:24
@kmvanbrunt If we do this, I think we should do it in a fairly generic and robust fashion where there is a degraded mode in which we have access to the normal Python `readline` package functionality but do **not** have access to the extended functionality for which we are using `ctypes` to directly call functions in the `readline` dynamic library which are not wrapped by Python's `readline` package.  There should also be a good warning message printed in yellow upon startup of a `cmd2` application functioning in this degraded mode notifying the user that this is happening.  Moreover, the Sphinx docs should be updated to explain what features are not available in this degraded mode.

We may also wish to submit a feature request and/or PR to CPython for wrapping the missing functionality which is necessitating our usage of `ctypes`.

**Closed** 2019-11-26 00:28 UTC
