### ISSUE TITLE
history -t should use StringIO -- v0.8.9

### ISSUE THREAD

**Issue by deargle** [python-cmd2/cmd2#694] opened 2019-06-05 06:43 UTC
https://github.com/python-cmd2/cmd2/blob/bf556dd93045eaa54940c64d53cd81aca219f835/cmd2.py#L3662-L3698 directly import `io`, and creates a string buffer using `io.StringIO()`, but this leads to unimplemented `fileno` complaints, when generating a transcript from `history -t`, e.g.:

```
Traceback (most recent call last):
  File "/home/deargle/.virtualenvs/psiturk-default/local/lib/python2.7/site-packages/cmd2.py", line 2476, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/deargle/.virtualenvs/psiturk-default/local/lib/python2.7/site-packages/cmd2.py", line 2675, in onecmd
    stop = func(statement)
  File "/home/deargle/.virtualenvs/psiturk-default/local/lib/python2.7/site-packages/cmd2.py", line 3254, in do_shell
    proc = subprocess.Popen(expanded_command, stdout=self.stdout, shell=True)
  File "/home/deargle/.virtualenvs/psiturk-default/local/lib/python2.7/site-packages/subprocess32.py", line 584, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/home/deargle/.virtualenvs/psiturk-default/local/lib/python2.7/site-packages/subprocess32.py", line 1110, in _get_handles
    c2pwrite = stdout.fileno()
AttributeError: StringIO instance has no attribute 'fileno'
EXCEPTION of type 'AttributeError' occurred with message: 'StringIO instance has no attribute 'fileno''
```

The top of the script already imports the correct version of `StringIO` depending on whether python 2 or 3. Fix is to do `membuf = StringIO()`  within the `def _generate_transcript` for loop, and remove the `import io` statement at the top of that def.

in python 2, cmd2 v0.8.9 (sorry, I'm working on upgrading to python 3...)

**Comment by tleonhardt** [comment] 2019-06-05 12:34
@deargle Thank you for the well written bug report complete with proposed solution!

Version [0.8.9](https://github.com/python-cmd2/cmd2/releases/tag/0.8.9) of `cmd2` was released in August 2018 and was intended to be the last version of `cmd2` released with support for Python 2.  We are now on version [0.9.12](https://github.com/python-cmd2/cmd2/releases/tag/0.9.12) with [0.9.13](https://github.com/python-cmd2/cmd2/blob/master/CHANGELOG.md) soon to be released.  Starting with version 0.9.0 we only support Python 3.  At this point Python 3 has been out for over 10 years and Python 2 will hit end-of-life on Jan 1, 2020 where after that it won't even get security updates.  So we wanted to spend our limited developer time making `cmd2` better as opposed to wasting time maintaining legacy compatibility which was getting more and more time consuming as time went on.

I don't believe this is a bug in Python 3.  If I am wrong, then we would be most happy to work on a fix.

If you want to put the fix in, I'd be happy to create a python2 branch based on our 0.8.9 tag and you could submit a PR from and to that branch.  If you find other bugs in Python 2 the same could be done and when you are happy with the state of things, I'd be happy to put out a 0.8.10 release with Python 2 support.

**Comment by tleonhardt** [comment] 2019-06-05 12:43
Oh random FYI, the latest version of `cmd2` added a `load -t` option for automatically generating transcripts based on an ASCII text script file.  This is generally faster and easier for developers which are trying to maintain a suite of regression tests based on transcripts.

**Comment by deargle** [comment] 2019-06-05 14:37
Sure, I can PR for an 8.10 -- hopefully I won't have much more to do before
I'm ready to move to python3. I did see the load -t option in more recent
cmd2's, I am envious.

The project I'm working on migrating has been around since 2012 and doesn't
(didnt) have unit tests, so i'm working on making those first before the
python3 migration. Hence the history -t call, for unit testing generation.
And yeah I think python3 is not affected by the stringio thing.

**Comment by tleonhardt** [comment] 2019-06-05 14:45
@deargle I invited you to the python-cmd2 GitHub organization.  This will allow you to directly create branches in our repo and push to branches other than master so you don't need to deal with a fork.  You can create a *python2* branch off of the **0.8.9** tag.  

One inefficiency you will encounter is that our continuous integration (CI) systems are all setup for Python3 only.  So testing will probably need to be manually done on that branch before committing.

**Comment by deargle** [comment] 2019-06-19 05:15
@tleonhardt I created a `python2` branch off of v0.8.9 and I got local tests passing for tox env py27 after resolving the output redirect character not being properly parsed by dadgum `pyparsing`. I'm back to working on writing python2 unit tests for my other project, so I may find other edits for the 0.8.10 milestone. Ah me for working on sunsetting code...

**Comment by tleonhardt** [comment] 2019-06-19 11:12
Yeah pretty much the very first thing we did after moving to Python 3 only was to rip out the usage of pyparsing entirely and replace it with shlex combined with a custom parser.  That made the code easier to maintain and it sped the unit tests up immensely.

Good luck with your unit tests for your other project!

**Comment by tleonhardt** [comment] 2019-09-08 16:57
I'm going to close this.  We no longer posses the infrastructure for properly testing on Python 2 prior to a release and we wouldn't want to risk potentially making things worse.

**Closed by tleonhardt** 2019-09-08 16:57 UTC

**Comment by deargle** [comment] 2019-09-08 18:42
K. Fwiw for anyone perchance googling this in the future, the python2
branch has all (both) of the changes that I was going to make, and they
passed local unit tests for me run via tox.

**Comment by tleonhardt** [comment] 2019-09-08 20:20
@deargle Thanks for your work on the python2 branch.  We will leave that around and probably apply a tag as well.
