### ISSUE TITLE
The default imports in __init__ causes significant lag

### ISSUE THREAD

**Issue by anselor** [python-cmd2/cmd2#369] opened 2018-04-23 21:58 UTC
I have a module where I hijack argcomplete's bash completion and tie it into the completion function provided by `AutoCompleter`. Since `AutoCompleter` is a part of `Cmd2` and `__init__` imports `Cmd` and a bunch of other things, it causes about half a second lag on my machine to perform tab completion in bash. If I comment out all of the imports in `__init__` there is no noticeable lag.

Since the next release is going to have a number of big changes anyway, I'm proposing we take out the default imports and force everyone to update their code to import from `cmd2.cmd2`. What do you guys think?

@tleonhardt @kmvanbrunt @kotfu

**Comment by anselor** [comment] 2018-04-23 22:37
Unfortunately it's the import of `cmd2.Cmd` that causes the lag. If we remove `cmd2.Cmd` from the default imports we may as well remove all of them.

**Comment by kotfu** [comment] 2018-04-24 01:59
Still formulating an opinion here, but the good news is that in the ply branch, where we no longer import pyparsing, importing `cmd2` takes about 60% as long as it does on the master branch.

**Comment by tleonhardt** [comment] 2018-04-24 02:40
I'd say go ahead and put in your PR where you make this change and include a demo example showing the use of the ``argparse`` auto-completion at the bash command line via the aid of ``cmd2``.  This does sound like a really nice capability.  I can just be a curmudgeon sometimes when it comes to backward incompatibility ...

I've loved everything else you have done, so I believe there is a high probability that I will love this too.

There will probably be numerous small changes required within the unit test and example code to deal with the default imports no longer being present.

**Comment by kmvanbrunt** [comment] 2018-04-24 02:51
I've seen the argcomplete/AutoCompleter module and it is very cool, so naturally I support removing the imports. Basically it gives you AutoCompleter in bash when typing arguments for a cmd2-based app.

I also understand how annoying it is for developers to have compatibility issues each time a new version of software comes out. Perhaps we should make 0.9.0 a release candidate version since it will incorporate so many new features. That will give developers time to update their code and us time to debug the new stuff. After we know its stable, we can release the final version as 1.0.0.

Thoughts?

**Comment by tleonhardt** [comment] 2018-04-24 03:01
I think it will be sufficient to just put big bold warnings in the release notes for 0.9.0 which mention the ways in which backwards compatibility has been broken - no need to call it a "release candidate" or anything like that.  

Historically, all of the 0.x.0 releases of ``cmd2`` have involved large changes including backwards incompatibilities.  So I think if there are backwards incompatible changes we would like to make, then making several together in the 0.9.0 release is probably better than making one every release.  

Better to make the changes we want now and hopefully gradually stabilize once we approach a 1.0.0 release.

**Comment by anselor** [comment] 2018-04-24 13:18
It's worth noting that the argcomplete hijacking technically doesn't require your cli to be a cmd2 app. I've isolated it from cmd2 such that you should be able to use it to use the AutoCompleter tab completion in bash for any script that uses argparse. It may make sense to split out AutoCompleter separately and borrow the bash script and installation that argcomplete uses.

**Comment by tleonhardt** [comment] 2018-04-24 14:02
I see some utility in leaving it within ``cmd2``, that way you can use the same library to assist with creating both non-interactive command line utilities (CLU) and interactive command line applications (CLI).

**Comment by anselor** [comment] 2018-04-24 14:08
argcomplete uses the Apache2 license and we're on MIT license here. I don't know how compatible the 2 licenses are.

**Comment by anselor** [comment] 2018-04-25 15:49
Ok, try this out. I've updated `examples/subcommand.py` to enable bash completion.

You'll need to install and set up [argcomplete](https://github.com/kislyuk/argcomplete) for this to work. 

Once you have it set up and start a new bash session you should see this:
`$ ./subcommands.py <tab>`
`bar    foo    sport `

`$ ./subcommands.py foo <tab>`
` >>>>>>>>>>>>>>>>>>>>>>  Hint:   Y        float`

`$ ./subcommands.py foo -<tab>`
`-h      --help  -x`

`$ ./subcommands.py foo -x <tab>`
` >>>>>>>>>>>>>>>>>>>>>>>>  Hint:   -x X     integer  `


Also, any suggestions for how to unit test bash completion?

**Comment by tleonhardt** [comment] 2018-04-25 23:09
You example works for me on Linux but not macOS, but I expect the failure lies solidly within ``argcomplete``.

I'm against adding a dependency on ``argcomplete``, but if I read your code correctly it is a fully optional dependency where if the end user doesn't have it installed then that feature isn't supported but the rest of the application will continue to work normally.  Is that correct?

**Comment by anselor** [comment] 2018-04-26 01:51
Yeah, the intent is for it to be optional. I think I can add a dependency in tox.ini so it'll be installed for the testing environment.

**Comment by tleonhardt** [comment] 2018-04-26 12:18
Yup you can just add it to tox.ini

**Comment by anselor** [comment] 2018-05-02 19:30
Merged with #379

**Comment by kotfu** [comment] 2018-05-06 18:53
Remember above when I said I was still formulating my opinion 🤔. Now it's formulated💡.

I am opposed to removing all of the imports from `__init.py__`.  Before you 🤬, lemme explain my thinking.

With an empty `__init.py__`, if someone wants to use the `AddSubmenu` decorator, they must first import it using `from cmd2.cmd2 import AddSubmenu`. If we decide to move that decorator into it's own source code file called `submenu.py`, then we break everyone's imports.

When we include import statements in `__init.py__` we shield users of `cmd2` from how we have organized our classes in the source code files. This is an important part of providing a stable external interface to our library.

I see the value in the quick startup time for integrating with bash completion. @anselor states that he observes "about half a second lag" when he hits the tab key on a shell command utilizing the capability. That's clearly too slow. I thought I would try and figure out if there is a way to keep a nice set of imports in `__init.py__` and still have speedy startup times.

As always, performance measurement is difficult to replicate, but measurement can help pinpoint potential problems. Here's some data I collected on my 2015 MacBook Pro.
```
$ time python -c ""

real	0m0.106s
user	0m0.057s
sys	0m0.043s
```

I use `pyenv` which shims every python executable. If I skip the shimming I can save 60 ms or so:
```
$ time ~/.pyenv/versions/cmd2-3.6/bin/python -c ""

real	0m0.038s
user	0m0.028s
sys	0m0.010s
```
That's pretty fast. There is some variation (maybe 10%) but it's generally around 40 ms. With an empty `__init.py__`, importing `cmd2` there is no appreciable difference in speed:
```
time ~/.pyenv/versions/cmd2-3.6/bin/python -c "import cmd2"

real	0m0.037s
user	0m0.025s
sys	0m0.010s
```

When `__init.py__` imports Cmd with `from .cmd2 import Cmd', the times go up:
```
time ~/.pyenv/versions/cmd2-3.6/bin/python -c "import cmd2"

real	0m0.157s
user	0m0.112s
sys	0m0.038s
```

On my machine, it takes ~120ms to import `cmd2`. I went through `cmd2.py` to see if I could figure out what the slow parts of importing were. It's death by a thousand cuts. Well, not quite a thousand, but we import 23(!) modules from the standard library. None of them are individually slow, but combined together it adds up.

Further digging reveals that many of these imported modules are only used in occasional circumstances, for example, the `glob` module is only used when you try and tab complete an executable or a filename, or when running transcript files.

I started commenting out imports to see which ones were not needed at the moment `cmd2` is imported. I identified 14 that could be commented out and still have the import work successfully. The time to import `cmd2` dropped from ~120ms to ~90ms. I believe that with a bit of work which would include moving some code out of `cmd2.py` and into it's own files, and lazy-loading the imports (i.e. instead of running the import at the top of `cmd2.py`, run the import just before using the imported code), we can maybe get to ~70ms to import `cmd2`.

I propose we re-open this issue, and I'll start a branch to see how much I can reduce the import time. After we see what improvements can be made, I suggest we re-evaluate the inclusion of imports in `__init.py__`.

**Comment by kotfu** [comment] 2018-05-08 15:25
I continued with more testing to see if I could make this faster. Something I did yesterday changed the time to run the import command from ~120ms to ~600ms. Which I'm guessing this longer import time is something like what @anselor noticed on his system. After further experimentation, I believe the cause of this slowness is not the code in `cmd2`.

I use `pyenv` and `virtualenv` to manage my python working environment. After the import went to 600ms on my MacBook Pro, I went to one of my other computers, a 5 year old hackintosh with 16GB ram, 4 core i7 and SSD. It was also taking ~600ms. I ran the following `cProfile` to see if I could see why the import was taking so long:

```
$ ~/.pyenv/versions/cmd2-3.6/bin/python -c 'import cProfile
> cProfile.run("import cmd2")
' | less
```

At the top of the output, `cProfile` shows how many function calls it made: 564,288. Upon scrolling through the output, I noticed that there were lots of calls in `pyparsing.py`. There should be no reason for cmd2 to be importing or calling `pyparsing`. I went back and ran the same command on my MacBook Pro, and it too had lots of calls to `pyparsing`. On both computers I also saw calls to other modules that we are no longer using, like `six`.

I decided to rebuild my `pyenv` environment and see if that made a difference. I did the following:
```
$ pyenv uninstall cmd2-3.6
$ pyenv virtualenv -p python3.6 3.6.4 cmd2-3.6
$ pip install colorama wcwidth pyperclip
$ time ~/.pyenv/versions/cmd2-3.6/bin/python -c "import cmd2"

real	0m0.141s
user	0m0.099s
sys	0m0.035s
```

I reran the `cProfile` command, and now there were only 49,275 function calls, 10% as many as before. The calls to `pyparsing.py` and `six.py` were gone. I went back to my MacBook Pro and rebuilt my python environment there, and saw the import time drop from ~600ms back down to ~140 ms.

I've attached the output of the two profiled imports.

[140ms.txt](https://github.com/python-cmd2/cmd2/files/1984564/140ms.txt)
[600ms.txt](https://github.com/python-cmd2/cmd2/files/1984565/600ms.txt)

@anselor, would you run the following on your machine and attach it?

```
$ python -c 'import cProfile
> cProfile.run("import cmd2")
' > anselor-import.txt
```

**Comment by anselor** [comment] 2018-05-08 15:51
I'm out of town right now without my dev environment with me. I'm using a
fairly unmodified Ubuntu 16.04 environment. I'll be b back home next week.

**Comment by tleonhardt** [comment] 2018-05-10 21:05
@kotfu @anselor @kmvanbrunt 
The 0.9.0 release is turning into a really huge one.  I'd like to get it out the door pretty soon if possible.  Perhaps by the end of next week? 

If everyone else is on board, then lets try to get this 500ms import problem nailed down by the end of next week if we can and then get the release out late next week or over the weekend.  And we should actually do an 0.8.6 release first containing backported bug fixes.

I think @kmvanbrunt has one more small change related to improved tab-completion of the **alias** command that he would like to get into this release.  If I can find any time I might try to work on either unit tests or type hinting a little more.  But I think we are definitely at the point where we want to get these massive changes out the door sooner rather than later.   Then 0.9.1 will likely end up mostly being a bug-fix release based on reports from end users.  They always manage to find some interesting cases we never thought of testing ;-)

**Comment by kotfu** [comment] 2018-05-16 23:59
Your assumption on which branch to test was correct. This profile shows lots of calls to modules that have nothing to do with `cmd2`, for example, `cache.py`, `calendar.py`, `gettext.py`, `magic.py`, our old friend `pyparsing.py`, and `textwrap.py`. This is similar behavior to what I noticed.

I'd like to gather some more information about your python environment. You mentioned you run on Ubuntu 16.04. 

What do you use for python binaries: the system python (i.e. the one installed by `apt`), or something like `pyenv` or `conda`?

Do you use a virtual environment for python packages, something like `venv` or `virtualenv`?

**Comment by anselor** [comment] 2018-05-17 05:06
I do this on an Ubuntu VM, with python installed through apt. I don't use any python virtual environments.

**Comment by anselor** [comment] 2018-05-17 05:07
Actually, I might be misremembering that. I think this one is on a Debian VM.

**Comment by anselor** [comment] 2018-05-17 22:34
Not everything upgraded during the force-reinstall. I skipped over the ones that didn't upgrade.
[anselor-import2.txt](https://github.com/python-cmd2/cmd2/files/2014918/anselor-import2.txt)
[anselor-pkgs.txt](https://github.com/python-cmd2/cmd2/files/2014919/anselor-pkgs.txt)

**Comment by kotfu** [comment] 2018-05-18 02:10
Were you on `speedup_import` branch or on `master` when you ran the profile commands?

**Comment by kotfu** [comment] 2018-05-18 02:48
One more request, would you post the output of the following command:
```
$ env | grep PY
```

**Comment by anselor** [comment] 2018-05-18 02:49
lol, was distracted and forgot to change over. I'll do it again tomorrow.

**Comment by anselor** [comment] 2018-05-18 14:05
[anselor-import2.txt](https://github.com/python-cmd2/cmd2/files/2017175/anselor-import2.txt)

Only thing in env with PY:
PYTHONPATH=:/home/user/src/cmd2

**Comment by tleonhardt** [comment] 2018-05-18 20:08
@anselor I see your import file bringing in a TON of stuff it really shouldn't be including all of the following:

- **six**
- **pyparsing**
- **pylab** (Matlab compatibility layer)

**Comment by kotfu** [comment] 2018-05-18 20:36
With `/home/user/src/cmd2` in PYTHONPATH, it not only puts `cmd2` in your import path, but every egg installed in place in `..src/cmd2` is on your import path too. I suggest the following:

1. Fix your shell init (if using bash it's in `.profile` or `.bash_profile` or `.bashrc`) to not set PYTHONPATH. Log out and log in again and ensure no PYTHONPATH environment variable exists.

2. Install `cmd2` "in-place" by:
```
$ cd /home/user/src/cmd2
$ sudo pip install -e .
```
This method still makes any changes to the `cmd2` source code instantly available, and has the added benefit of making the package show up when you do `pip list`.

3. Remove eggs and cached python byte code:
```
$ cd /home/user/src/cmd2
$ rm -rf .eggs
$ rm -rf *.egg-info
$ rm -rf *.egg
$ find . -name __pycache__ -exec rm -rf {} \;
```
That last command finds and removes all the byte code caches.

4. Re-run the import profiler (again):
```
$ python -c 'import cProfile
> cProfile.run("import cmd2")
' > anselor-import3.txt
```
and attach `anselor-import3.txt` to this thread.

**Comment by tleonhardt** [comment] 2018-05-18 20:50
@kotfu I fear I might be fundamentally to blame for this ;-(  

I didn't know about the way to install ``cmd2`` "in-place" using **pip**, so in the [Contributor's Guide](https://github.com/python-cmd2/cmd2/blob/master/CONTRIBUTING.md) I recommended all contributor's to the project to follow my PYTHONPATH hack.

So I guess as part of this Issue one way or another, somebody should update the **CONTRIBUTING.md** file to recommend the better way of:

```Bash
$ cd /home/user/src/cmd2
$ sudo pip install -e .
```

**Comment by kotfu** [comment] 2018-05-18 23:13
No worries @tleonhardt. I updated both `setup.py` and `CONTRIBUTING.md` with the modern recommendations for an editable install (`pip install -e .`) and for installing development dependencies (`pip install -e .[dev]`).

**Comment by anselor** [comment] 2018-05-19 15:54
I'm on my laptop this weekend with a different VM and didn't take a snapshot before replicating these steps. How do I uninstall after doing `pip install -e` - pip says there's nothing to uninstall. I'm now unable to verify that I had the same behavior here before I made these changes so I'm unable to verify (until Monday) that these steps resolve the slowness I was seeing. 

 I'm attaching the result from this machine after the changes but I don't know how valid it is since I couldn't verify it was present before.
[anselor-import4.txt](https://github.com/python-cmd2/cmd2/files/2019605/anselor-import4.txt)
@kotfu

**Comment by kotfu** [comment] 2018-05-19 16:37
Here's a series of commands that shows how to install, check, and uninstall an "editable" or "in place" package:
```
$ cd /home/kotfu/src/cmd2
$ pip install -e .
$ pip list | grep cmd2
cmd2              0.9.0   /home/kotfu/src/cmd2
$ pip uninstall cmd2
$ pip list | grep cmd2
```

**Comment by kotfu** [comment] 2018-05-19 16:44
`anselor-import4.txt` looks much better. Less than 50,000 calls, no extra modules being imported, and completed in ~350ms. I hope this works on your other VM.

**Comment by anselor** [comment] 2018-05-19 17:13
Yeah, I'll have to try it again when I'm back in the office Monday. 

pip appears to have forgotten where it's recording that cmd2 is installed in place. It shows cmd2 in pip list but if I try pip uninstall it says it can't find cmd2.

**Comment by anselor** [comment] 2018-05-19 17:38
Yeah, I tried both with and without sudo - it doesn't matter - pip doesn't know that cmd2 is installed even though it shows up in the list.

**Comment by anselor** [comment] 2018-05-19 17:41
Multiple unit tests that previously worked fine also failing now. I may have to just blow this VM away and start over.

**Comment by tleonhardt** [comment] 2018-05-19 19:35
@anselor 

I've been doing some testing using the current *master* branch on different OSes and different versions of Python to see if I can reproduce any of your unit test failures.

All unit tests pass for all of the following OS/Python combinations:
* macoS
    * Anaconda Python 3.6
    * Anaconda Python 3.5 
* Linux
    * Ubuntu 17.10 Python 3.6 from apt-get
* Windows 10
    * Anaconda Python 3.6

Unit test failures I encountered are as follows:
* macoS
    * Anaconda Python 3.4
        * Error collecting tests from **test_completion.py** and **test_bashcompletion.py** because **argcomplete_bridge.py** module has no attribute ``FilesCompleter``
* Linux
    * Debian 9.4 Python 3.5 from apt-get
        * Weird errors related to file descriptors.  To me it seems like these are likely errors in **pytest** and/or one of the **pytest** plugins

**Comment by anselor** [comment] 2018-05-19 20:09
The VM I'm using right now is Ubuntu 16.04 with Python 3.5 from apt and I'm seeing the weird monkeypatch errors as well as weird errors from file descriptors. 
I tried changing the monkeypatch tests to use pytest-mock and they succeed on linux but fail on Windows.

**Comment by anselor** [comment] 2018-05-21 15:12
Back on the problem VM today. Removed the entry from PYTHON_PATH and did an in-place install. Started a fresh terminal session, verified PYTHON_PATH is clear and got this:
[anselor-import5.txt](https://github.com/python-cmd2/cmd2/files/2023074/anselor-import5.txt)

**Comment by kotfu** [comment] 2018-05-21 15:49
Still super slow. So let me summarize what we know:

@anselor has a linux distro using system python, which imports a bunch of extra modules when you import `cmd2`, resulting in long wall time to do the import. @kotfu noticed a similar phenomenon on macOS using `pyenv` and `virtualenv`. @kotfu fixed his problem by re-creating the virtualenv. @anselor got rid of PYTHON_PATH in favor of an editable install, and reinstalled all the packages, but the issue persists. @anselor tried it on a different VM and did not observe the issue.

@kotfu made some changes in the *speedup_import* branch, which just defer importing certain infrequently used modules until the user takes some action which requires the module. This can reduce the cycles required to import `cmd2`, but these changes do not address the root cause, and only make incremental improvement.

Based on these facts, it appears that we still don't understand the root cause of the issue. We have a couple of instances where it occurs, but it doesn't always occur. My current best guess is that this is caused by something outside of `cmd2` code.

I think this is the only issue holding up release of 0.9.0, I guess we need to decide if we want to continue to hold up the release until we get this resolved. Options for how to move forward are:

1. move forward with release of 0.9.0 without merging *speedup_import* and indicate in the changelog that we have this potential issue under investigation
2. merge *speedup_import* and release 0.9.0, with a similar note in changelog that we are investigating this issue
3. continue to investigate this issue and get it resolved before releasing 0.9.0

I'm leaning towards option 1. What does everybody else think?

**Comment by kotfu** [comment] 2018-05-21 15:54
Oh yeah, I forgot to mention, I still feel pretty strongly that we should have a robust set of imports in `cmd2/__init__.py`, which are not currently there. These imports provide a level of indirection between the organization of our source code and how uses import our classes.

So I guess if we decide to release 0.9.0 without resolving the slow import issue, we need to also decided whether to leave `__init.py__` with no imports (which is how *master* currently is), or modify it to have a robust set of imports.

**Comment by tleonhardt** [comment] 2018-05-21 18:46
@anselor I still see a ton of imports which just shouldn't be there for just ``cmd2`` such as ``six``, ``pyparsing``, and ``pylab``.  So something is amiss on that VM.  Can you have @kmvanbrunt check on his VM and/or check on the VM used by the Jenkins build system or my old VM?

@kotfu I would like to move forward with the 0.9.0 release within the next week or so just because it is getting very large.  But at the same time I would like to find some sort of compromise solution which is acceptable to everyone with the intent that we continue working on this issue to get to the bottom of it.  Along those lines, I think it would be a good idea to merge the *speedup_import* changes into *master*.

@kmvanbrunt @kotfu @anselor 
What would you think about a compromise solution for the imports which at least for now leave some of them there, but removes the import of the **Cmd** class?  Does that fix any of the speed problems?

**Comment by kotfu** [comment] 2018-05-21 19:04
I don't think a compromise of having some imports but not the **Cmd** class is a good idea. If we don't automatically import the **Cmd** class as **cmd2.Cmd**, we will break every single app out there when we release 0.9.0. Everyone will go fix their code to use **cmd2.cmd2.Cmd** and we will have lost one major benefit of having the imports in `__init__.py`: backwards compatibility. The compromise would (I'm 99% sure) solve the import speed problem, I'll have to do some more testing to verify, but it would be easy to do.

**Comment by tleonhardt** [comment] 2018-05-21 19:18
@anselor If it proves difficult to solve the performance issues, then maybe we should consider moving the **argcomplete_bridge** functionality to its own module separate from ``cmd2``.  

Personally I like having it inside ``cmd2`` for the "one-stop-shop" aspect of it where ``cmd2`` can help you quickly create features rich interactive command-line interface applications (CLIs) as well as non-interactive command-line utilities (CLUs).  

However, from an architectural perspective the **argcomplete_bridge** code is mostly unrelated to the rest of the ``cmd2`` code base and may be better as a separate module - that way CLUs which want to use it don't need to import anything from ``cmd2`` and won't pay any associated performance/latency penalty.  If you want, it should be very easy to create a new repo underneath the top-level **python-cmd2** organization if you wish.

**Comment by tleonhardt** [comment] 2018-05-23 20:17
I haven't seen anything on this issue in the past couple days?  Does anyone have any thoughts or opinions on how to move forward.  I'd like to put out the 0.9.0 release by the end of May if possible.

**Comment by tleonhardt** [comment] 2018-05-23 22:30
@kotfu That plan sounds reasonable to me.

**Comment by kotfu** [comment] 2018-05-25 01:11
PR #413 does not completely resolve this issue, but there is some progress. Keeping this issue open until we completely resolve.

Two files are now present in **master** branch related to this issue, which should be deleted when we resolve.

- `mtime.sh` - simple script to run a command 100 times and print the average wall time of running the command
- `speedup_import.md` documentation on changes made to reduce import times and progress noted from each change.

**Comment by tleonhardt** [comment] 2018-05-27 15:39
Random train of thought, one thing which can cause weird import behavior is if you have old *.pyc files and/or ``__pycache__`` directories lying around.

If can be worth using the **find** command to remove all of these:
```Bash
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
```

**Closed** 2018-06-09 19:48 UTC
Labels: enhancement
